//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.06 at 10:56:49 AM MESZ 
//


package org.kalypso.ftp.service.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kalypso.ftp.service.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FtpService_QNAME = new QName("schema.service.ftp.kalypso.org", "FtpService");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kalypso.ftp.service.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FtpServiceType }
     * 
     */
    public FtpServiceType createFtpServiceType() {
        return new FtpServiceType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FtpServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "schema.service.ftp.kalypso.org", name = "FtpService")
    public JAXBElement<FtpServiceType> createFtpService(FtpServiceType value) {
        return new JAXBElement<FtpServiceType>(_FtpService_QNAME, FtpServiceType.class, null, value);
    }

}
