//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.06 at 10:56:49 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "schema.service.ftp.kalypso.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.kalypso.ftp.service.schema;
